version: "3.8"
services:
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 192837465s
      MYSQL_DATABASE: doctor_service
      MYSQL_USER: postgres
      MYSQL_PASSWORD: 102837465s
    ports:
      - "3306:3306"
  app:
    build: .
    ports:
      - "5002:5002"
    depends_on:
      - db
    environment:
      DB_HOST: localhost
      DB_USER: postgres
      DB_PASSWORD: 192837465s
      DB_NAME: doctor_service
